// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3uLpooQ9xHQth2j1Ppk0j9FTUgI_N3g',
    appId: '1:366898772885:web:9833c1721ddadece52149c',
    messagingSenderId: '366898772885',
    projectId: 'my-incrementer-app',
    authDomain: 'my-incrementer-app.firebaseapp.com',
    storageBucket: 'my-incrementer-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IbQjYRucMBwCIid9ziZy4Jtu_zRQLY0',
    appId: '1:366898772885:android:ead2f5d62fa94d3252149c',
    messagingSenderId: '366898772885',
    projectId: 'my-incrementer-app',
    storageBucket: 'my-incrementer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ08Vsm0CJm-Rqkp4dlCmOF-Fm553ulDU',
    appId: '1:366898772885:ios:45dbd78db25c939752149c',
    messagingSenderId: '366898772885',
    projectId: 'my-incrementer-app',
    storageBucket: 'my-incrementer-app.appspot.com',
    iosBundleId: 'com.example.incrementerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ08Vsm0CJm-Rqkp4dlCmOF-Fm553ulDU',
    appId: '1:366898772885:ios:45dbd78db25c939752149c',
    messagingSenderId: '366898772885',
    projectId: 'my-incrementer-app',
    storageBucket: 'my-incrementer-app.appspot.com',
    iosBundleId: 'com.example.incrementerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3uLpooQ9xHQth2j1Ppk0j9FTUgI_N3g',
    appId: '1:366898772885:web:5f95dd430233a51452149c',
    messagingSenderId: '366898772885',
    projectId: 'my-incrementer-app',
    authDomain: 'my-incrementer-app.firebaseapp.com',
    storageBucket: 'my-incrementer-app.appspot.com',
  );
}
